### ISSUE TITLE
práctica 

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-3-practica-architect-NoeliaGlez#1]
[ReporteDiagramaDeClases.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-NoeliaGlez/files/9492227/ReporteDiagramaDeClases.pdf)

**Comment by EdwinOrtiz1412** [comment]
Calificación: 16

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
